import 'package:flutter/material.dart';

import '../../core/constants/otc_assets.dart';
import '../../core/services/app_scope.dart';
import '../../core/theme/app_colors.dart';
import '../../models/otc_asset.dart';
import '../../widgets/cards/asset_grid.dart';
import '../../widgets/layout/responsive_body.dart';
import '../../widgets/layout/section_header.dart';

class MarketsScreen extends StatefulWidget {
  const MarketsScreen({super.key});

  @override
  State<MarketsScreen> createState() => _MarketsScreenState();
}

class _MarketsScreenState extends State<MarketsScreen> {
  AssetCategory? _category;
  String _query = '';

  @override
  Widget build(BuildContext context) {
    final colors = context.tpColors;
    final settings = AppScope.settings(context);
    final q = _query.trim().toLowerCase();
    bool matches(OtcAsset asset) =>
        q.isEmpty || asset.symbol.toLowerCase().contains(q);
    final visible = _category == null
        ? AssetCategory.values
        : [_category!];

    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        title: const Text('Markets'),
        automaticallyImplyLeading: false,
      ),
      body: ResponsiveBody(
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            Text(
              'Simulated OTC assets. Prices are generated by the demo market engine.',
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: colors.mutedText,
                  ),
            ),
            const SizedBox(height: 12),
            TextField(
              decoration: const InputDecoration(
                hintText: 'Search BTC, EUR, GOLD…',
                prefixIcon: Icon(Icons.search),
              ),
              onChanged: (value) => setState(() => _query = value),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _CategoryChip(
                  label: 'All',
                  selected: _category == null,
                  onTap: () => setState(() => _category = null),
                ),
                for (final category in AssetCategory.values)
                  _CategoryChip(
                    label: OtcAssets.categoryLabel(category),
                    selected: _category == category,
                    onTap: () => setState(() => _category = category),
                  ),
              ],
            ),
            const SizedBox(height: 20),
            for (final category in visible) ...[
              () {
                final assets = OtcAssets.all
                    .where((item) => item.category == category && matches(item))
                    .toList()
                  ..sort((a, b) {
                    final fa = settings.isFavorite(a.symbol);
                    final fb = settings.isFavorite(b.symbol);
                    if (fa == fb) return a.symbol.compareTo(b.symbol);
                    return fa ? -1 : 1;
                  });
                if (assets.isEmpty) return const SizedBox.shrink();
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    SectionHeader(title: OtcAssets.categoryLabel(category)),
                    const SizedBox(height: 12),
                    AssetGrid(assets: assets),
                    const SizedBox(height: 24),
                  ],
                );
              }(),
            ],
          ],
        ),
      ),
    );
  }
}

class _CategoryChip extends StatelessWidget {
  const _CategoryChip({
    required this.label,
    required this.selected,
    required this.onTap,
  });

  final String label;
  final bool selected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final colors = context.tpColors;
    return ChoiceChip(
      label: Text(label),
      selected: selected,
      onSelected: (_) => onTap(),
      selectedColor: colors.accent.withValues(alpha: 0.2),
      labelStyle: TextStyle(
        color: selected ? colors.accent : colors.mutedText,
        fontWeight: selected ? FontWeight.w600 : FontWeight.w400,
      ),
      side: BorderSide(
        color: selected ? colors.accent : colors.cardBorder,
      ),
    );
  }
}
